### ISSUE TITLE
dbt-osmosis yaml commands create � character when propagating column description

### ISSUE THREAD

**Issue by qferonH** [z3z1ma/dbt-osmosis#123]
Hi, I’m using the dbt-osmosis package on my dbt projects. Every time I run the dbt-osmosis yaml document ... command, many characters are transformed into ‘�’, which subsequently causes errors. The characters that are converted into ‘�’ are typically those with accents (as some of the descriptions are in French), but other symbols such as ‘…’ or ‘€’ are also transformed, which can be quite problematic. Do you know if there’s a parameter I can change to avoid this situation, or if there’s something that can be done on your end?

Thanks in advance.

**Comment by z3z1ma** [comment]
I added an env var on `main` branch called `DBT_OSMOSIS_ENCODING`

Try playing with that variable, perhaps setting it to `DBT_OSMOSIS_ENCODING=utf-16`
If you know the appropriate encoding up front, it *should* work but I'll keep this open for a bit until you confirm @qferonH
