### ISSUE TITLE
Allow docs block descriptions to propagate un rendered.  

### ISSUE THREAD

**Issue by VDFaller** [z3z1ma/dbt-osmosis#128]
## Problem
When I do `dbt-osmosis yaml document whatever` if it has a docs block upstream, it ends up putting the compiled markdown.  I'd love it if it could do just keep it the docs block.  I looked for closed issues around docs blocks so I hope I'm not duplicating something already done. 

dbt-databricks==1.6.6
dbt-core==1.6.9
dbt-osmisis==0.12.4

If you think this is doable, I'm happy to help with the MR.  

**Edit** Looking further it looks like it reads from the manifest. Which is fully compiled so this isn't a layup.  But maybe we could pull in the `node.original_file_path` then manually load the columns descriptions?  Not sure if it's antithetical to your goals.  

```python
node = {"database": "my_db",
    "schema": "my_schema",
    "name": "my_source",
    "resource_type": "source",
    "package_name": "my_dbt",
    "path": "models\\staging\\my_schema\\_my_schema__sources.yml",
    "original_file_path": "models\\staging\\my_schema\\_my_schema__sources.yml", 
    "source_name": "my_schema"
}

with Path(node['original_file_path']).open() as f:
    data = yaml.safe_load(f)
    
source_dict = next((item for item in data['sources'] if item['name'] == node['source_name']), None)
model_dict = next((item for item in source_dict['tables'] if item['name'] == node['name']), None)
```

**Comment by z3z1ma** [comment]
Yep your on the money. We would need to read the YAML and store the raw form.
It might be something I can work on but also open to PR

**Comment by VDFaller** [comment]
I'll try to make some time to work on it.  Anything I need to do special to contribute?

**Comment by z3z1ma** [comment]
Commented on the PR
