### ISSUE TITLE
VS Code - Osmosis Execute DBT SQL feature failing

### ISSUE THREAD

**Issue by MurugR** [z3z1ma/dbt-osmosis#13]
Hello and thanks for looking at my issue. When I click on this button after opening a model sql file in VS Code,
![image](https://user-images.githubusercontent.com/80878454/192205026-32cd80da-04f9-4c78-a79e-66a21c2e982f.png)

I get this error. 
![image](https://user-images.githubusercontent.com/80878454/192205242-cdf9de9e-4ff8-4c34-8116-84ec4c17faf1.png)

The actual path is c:\\\Temp\\git\au-nvg-business-intelligence\\\dbt\navigate_bi\\\dbt_project.yml. Because there are single backslashes in 2 spots (\au-nvg-xxx and \navigate_bi\\xxxx), both are being translated to \a and \n. I don't know why a mixture of single and double backslashes are coming in the file name and path. 

I've had to put a temp fix in osmosis.py in line 181 to get this working. See project_dir being added with replace calls. 

```
args = PseudoArgs(
            threads=threads,
            target=target,
            profiles_dir=profiles_dir,
            #project_dir=project_dir,
            project_dir=project_dir.replace('\t', '\\t').replace('\n', '\\n').replace('\r', '\\r').replace('\a', '\\a'),
        )
```

**Comment by MurugR** [comment]
Hi, 

Please refer to https://github.com/innoverio/vscode-dbt-power-user/issues/130. By following @mdesmet's advise and moving the flexibility down to targets, I got to keep the profile name static. This has also fixed the issue reported above. 

![image](https://user-images.githubusercontent.com/80878454/192918222-45a01afe-7d2a-49a7-8e6d-646ab94a5790.png)

**Comment by z3z1ma** [comment]
Closing this issue as resolved!
