### ISSUE TITLE
`compiled_sql` renamed to `compiled_code` from dbt 1.3 onwards

### ISSUE THREAD

**Issue by b-per** [z3z1ma/dbt-osmosis#14]
Hi! I just wanted to mention that from dbt version 1.3 onwards, the field `compiled_sql` from `manifest.json` has been renamed to `compiled_code` (to be relevant for Python models as well).

I tried the integration of dbt-osmosis into dbt PowerUser on a repo with 1.3b and got errors when I wanted to preview the data. 

Happy to create a PR to cater for `compiled_code` if you want me to!

**Comment by z3z1ma** [comment]
Thanks for the issue!

I am on a roll with the [v2](https://github.com/z3z1ma/dbt-osmosis/blob/main/src/dbt_osmosis/core/server.py) of the `dbt-osmosis server` so I went ahead and introduced a compat change in the just released version, 0.8.1 that factors in that change in the dbt api.

Please upgrade if needed and let me know how it goes!
Closing the issue in the meantime.
