### ISSUE TITLE
LLM Model?

### ISSUE THREAD

**Issue by bkimjin** [z3z1ma/dbt-osmosis#142]
Hi, this isn't necessarily an issue, but what is the context behind adding openai to `dbt-osmosis`? I couldn't find any patch notes related to it, and the [relevant file](https://github.com/z3z1ma/dbt-osmosis/blob/main/src/dbt_osmosis/core/llm.py) doesn't seem to do anything at this time.

**Comment by z3z1ma** [comment]
Its a placeholder because I had planned to add LLM support to automatically generate all the missing YAML for a given project. At least to stub it out to the best of the ability of the LLM given the available context.

**Comment by z3z1ma** [comment]
Moved to an optional dep in 0.13.0 to not mess with anyones dep resolver or add unnecessary deps.

**Comment by z3z1ma** [comment]
@bkimjin this is now actually implemented. Please give it a whirl by passing `--synthesize` to refactor or document cmds. And remember to install the extra.

https://github.com/z3z1ma/dbt-osmosis/blob/main/src/dbt_osmosis/core/osmosis.py#L1930
