### ISSUE TITLE
Support for dbt 1.9.0

### ISSUE THREAD

**Issue by FrankTub** [z3z1ma/dbt-osmosis#187]
When trying to install dbt-osmosis and dbt-core `1.9.0` into a virtual environment the following error is returned:

```shell
The conflict is caused by:
    The user requested dbt-core==1.9.0
    dbt-postgres 1.9.0 depends on dbt-core>=1.8.0
    dbt-osmosis 0.13.2 depends on dbt-core<1.9 and >=1.6

```

**Comment by syou6162** [comment]
We are preparing for dbt 1.9 at https://github.com/z3z1ma/dbt-osmosis/pull/186

**Comment by FrankTub** [comment]
Awesome @syou6162 !

**Comment by z3z1ma** [comment]
This is now merged. Thanks @syou6162 🔥
