### ISSUE TITLE
Investigate and Fix PyPI Release Failure for dbt-osmosis 0.13.3

### ISSUE THREAD

**Issue by syou6162** [z3z1ma/dbt-osmosis#188]
As you may have noticed, it seems that the release of the package from https://github.com/z3z1ma/dbt-osmosis/commit/93ef2030e2959edb5976a69ec29e9d98ed684259 to pypi has failed (release of `dbt_osmosis-0.13.3`).

The yml file for the release hasn't been modified recently, so it's possible that the settings for pypi have changed.

- https://github.com/z3z1ma/dbt-osmosis/blob/main/.github/workflows/release.yml

@z3z1ma I think that only the package administrator knows the repository settings and pypi settings, so could you please check for any configuration errors?

**Comment by z3z1ma** [comment]
Will check this out today. It was publishing a dev release to test pypi (https://test.pypi.org/). I need to look into that service / account to make sure it wasnt recycled.

**Comment by z3z1ma** [comment]
But I will cut a new tagged version release today either way.

**Comment by bkimjin** [comment]
@z3z1ma it looks like the latest release failed with a bad request: https://github.com/z3z1ma/dbt-osmosis/actions/runs/12347977851/job/34455974938

**Comment by syou6162** [comment]
@z3z1ma I found https://github.com/z3z1ma/dbt-osmosis/releases/tag/v0.14.0 is released 🎉 . Thank you for your release handling!
