### ISSUE TITLE
IPv6 issue

### ISSUE THREAD

**Issue by SBurwash** [z3z1ma/dbt-osmosis#25]
Good day, 

When trying to run the server within docker, I'm getting the error 
```
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 8581, 0, 0): cannot assign requested address
```

I'm guessing this is because the program was written on IPv6 instead of IPv4. I was wondering if it would be possible to support IPv4 as well.

Thanks!

**Comment by z3z1ma** [comment]
Thanks for the issue!

I will look into this. It sounds strange. Will try to reproduce.

**Comment by SBurwash** [comment]
Thanks @z3z1ma ! If you need any help / additional information, please let me know

**Comment by SBurwash** [comment]
Solution -> Specifying the IPv4 address solve this problem:

```
server serve --host 127.0.0.1 --port 8581 --profiles-dir ${DBT_OSMOSIS_PROFILES_DIR}
```
