### ISSUE TITLE
dbt-osmosis Public streamlit app is broken 

### ISSUE THREAD

**Issue by sambradbury** [z3z1ma/dbt-osmosis#33]
The sample streamlit app linked in the README returns an error. 

Broken link: https://z3z1ma-dbt-osmosis-srcdbt-osmosisapp-4y67qs.streamlit.app/

Screenshot: 
![Screen Shot 2022-12-05 at 18 57 29](https://user-images.githubusercontent.com/31943456/205779640-542a35f3-9147-4778-baec-b111d894cf73.png)

**Comment by z3z1ma** [comment]
The streamlit app is now back up and running 🥇
