### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JonCrawford** [z3z1ma/dbt-osmosis#47]
I know there's been a lot of changes in the SQLFluff, DBT, and VSCode world that has had an effect on dbt-osmosis's compatibility. Are we planning to update the project or should we assume it's not getting forward compatibility?

**Comment by z3z1ma** [comment]
Yes @JonCrawford , I plan on shifting it to rely on https://github.com/z3z1ma/dbt-core-interface
I have taken a shot at it already and its probably pretty close. I have just been short on time with a couple of OSS efforts projects I am pushing over the line.

**Comment by z3z1ma** [comment]
Took a first stab at a release, leveraging vendored interface that should be compatible with everything. New version is `0.10.0` on pypi. Exclusively focused on the `yaml` commands for now.
@JonCrawford

**Comment by JonCrawford** [comment]
You're awesome. The YAML commands were so clutch.

Just tried to check out the new lib, but my dbt-core is too new. Will watch for updates!
