### ISSUE TITLE
Misalignment between GitHub and PyPi releases?

### ISSUE THREAD

**Issue by followingell** [z3z1ma/dbt-osmosis#49]
As per subject line, I'm trying to understand why the latest release on GitHub is [`0.10.3`](https://github.com/z3z1ma/dbt-osmosis/releases/tag/0.10.3) however, on PyPi it's [`0.10.8`](https://pypi.org/project/dbt-osmosis/0.10.8/) at time of writing.

It _seems_ like this should be aligned but maybe there is something I am not taking into consideration...

**Comment by z3z1ma** [comment]
The github release process is not automated currently. PyPi has the correct version and you can see it reflected here in the [pyproject.toml](https://github.com/z3z1ma/dbt-osmosis/blob/main/pyproject.toml#L3)

Automating it is a valid todo, but it could also be deferred if I put a disclaimer in the docs that pypi is the source of truth. I'll take a look tomorrow.

**Comment by z3z1ma** [comment]
This is done now via set up of a github actions release flow.
