### ISSUE TITLE
[fix] extra newlines

### ISSUE THREAD

**Issue by hbwhbw** [z3z1ma/dbt-osmosis#5]
Maybe just on Windows: yml files with comments "#" in the original file end up getting an extry newline after each comment.  For example, typically people comment out tests like this:
```
  - name: my_column
    description: exactly what you want it to mean
      #        tests:
      #          - not_null

  - name: next_column
```
But this comes out the other side of a dbt-osmosis run as:
```
  - name: my_column
    description: exactly what you want it to mean
      #        tests:

      #          - not_null


  - name: next_column
```
Note that this is pretty horrible because if you run it multiple times, then each run that changes the file will introduce a new blank line for every comment and the file will just explode.

**Comment by z3z1ma** [comment]
This is not happening for me and I cant recreate. Lets re-open if more people experience this issue otherwise it might be isolated to a conflicting ruamel yaml installation or older version.
