### ISSUE TITLE
dbt-osmosis refactor not working with models that are dependant on seeds

### ISSUE THREAD

**Issue by edgga** [z3z1ma/dbt-osmosis#56]
Hello, 

so as stated in the issue title, I am having issues when doing .yaml refactoring for dbt models that reference dbt Seeds. The error I am receiving: 
`Error occurred while processing model model.test_project.test_model: 'SeedNode' object has no attribute 'depends_on' `

dbt version: 1.4.4

Installed packages:
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
  - package: calogica/dbt_date
    version: [">=0.7.0", "<0.8.0"]
  - package: Snowflake-Labs/dbt_constraints
    version: [">=0.5.0", "<0.6.0"]
  - package: dbt-labs/segment
    version: [">=0.9.0", "<1.0.0"]
  - package: dbt-labs/codegen
    version: [">=0.9.0", "<1.0.0"]
  - package: brooklyn-data/dbt_artifacts
    version: [">=2.2.0", "<2.3.0"]
  - package: dbt-labs/dbt_external_tables
    version: [">=0.8.0", "<1.0.0"]

Let me know if there's anything I can help you with and keep up the good work! Thanks.

**Comment by z3z1ma** [comment]
Thanks for the report @edgga ! 🔥 

Fixed in last patch release: `dbt-osmosis==0.11.17`
we will now do a safety check to ensure the attribute exists as we are building the knowledge graph.
