### ISSUE TITLE
Feature request - Add ability to "skip" adding all columns to models

### ISSUE THREAD

**Issue by b-per** [z3z1ma/dbt-osmosis#61]
The default feature of adding all columns to models is great but it can generate a huge diff in the YML files.

I think it would be useful to provide an option where documented columns are "pushed down" to downstream models but where non-documented columns are not added. I see it as a potentially first step in getting better docs without being to overwhelming..

**Comment by z3z1ma** [comment]
This is added in latest release via a flag called `--skip-add-columns` 
Version 0.11.19
https://github.com/z3z1ma/dbt-osmosis/releases/tag/v0.11.19
