### ISSUE TITLE
Feature request: Fuzzy matching on column name for inheritance

### ISSUE THREAD

**Issue by tobiascadee** [z3z1ma/dbt-osmosis#66]
I think this was already mentioned in the docs but letting know that the feature is wanted as well.
We use prefixes in our marts layer to show what group a column is a part of. We also use specific prefixes for dates and id columns. It would be great if there was an option to do fuzzy matching or maybe end of string matching for the column documentation inheritance!

**Comment by awoehrl** [comment]
Yes, fuzzy matching would be a great feature. We are renaming fields from camelCase to snake_case and it would be really helpful if dbt-osmosis could understand the connection.

**Comment by z3z1ma** [comment]
Open to PRs, its not difficult in theory. But I don't have time just yet. I know this would solve a major use case though given the typical dbt usage pattern

**Comment by tobiascadee** [comment]
@z3z1ma I will see if I can make some time to work on it!
