### ISSUE TITLE
AttributeError 'NoneType' object has no attribute 'current'

### ISSUE THREAD

**Issue by hcylia** [z3z1ma/dbt-osmosis#7]
I'm having this error :
```
    if SCHEMA_FILE.current is None:
AttributeError: 'NoneType' object has no attribute 'current'
```
Looking at the code in `main.py` and `app.py`, I've notices many things.

Here is an extract of the content of the « project » variable (dict) :
`{'name': 'MYPROJ', 'version': '1.0.1', 'project-root': 'my/path/MYPROJ/dbt', ....}`

But in the scipt, to get the name and root path of the project it's done like that : 
`project.project_name` instead of `project.name`
`project.project_root` instead of `project.project-root`

And SCHEMA_FILE is None because the `proj` variable, that should contain `project.project_name` => `MYPROJ `value, has : `my/path/MYPROJ/dbt`. 
And `node.get("package_name")` = `MYPROJ`
So the test comparing "`node.get("package_name") == proj`" is always `False` so SCHEMA_FILE is logically None.

**Comment by nchelaru** [comment]
I’m getting the same error, is it on the roadmap to fix this?

Great tool, by the way! :)

**Comment by z3z1ma** [comment]
Resolved!
