### ISSUE TITLE
Feature Request: data types added to columns in .yml

### ISSUE THREAD

**Issue by connor-lough** [z3z1ma/dbt-osmosis#71]
With the new constraints feature in dbt 1.5, you can enable `constraints`. However, unlike the dbt_constraints package (by Snowflake), with dbt's 1.5 constraints you un/fortunately have to enable `contracts` which requires listing out every column and its data type.
dbt-osmosis already goes into Snowflake INFORMATION_SCHEMA to reorder columns, it'd be great if it could add in data types!

**Comment by connor-lough** [comment]
Going to take a stab at this myself. Will keep issue thread updated.

**Comment by nurikk-sa** [comment]
Hi @connor-lough! Do you still work on this feature?
