### ISSUE TITLE
When dbt-osmosis encounters a character it can't process it leaves a whole .yml blank. It should only skip that char

### ISSUE THREAD

**Issue by alittlesliceoftom** [z3z1ma/dbt-osmosis#77]
"
ERROR    Error occurred while processing model        osmosis.py:940
         model.myproj.mymodel: 'charmap' codec               
         can't encode character '\u2705' in position                
         0: character maps to <undefined>   
"
Leads to mymodel.yml being blank. 

Ideally this should put in a standard placeholder char *?* but continue raising a warning.

**Comment by z3z1ma** [comment]
This should be resolvable via the `DBT_OSMOSIS_ENCODING` env var on `main`
I will cut a release soon

**Comment by alittlesliceoftom** [comment]
Ah nice! Thank you!
